spring.application.name=ECIReserves

spring.data.mongodb.uri=mongodb+srv://Calderon:Carito00$@fdsi.q1ewpfb.mongodb.net/?appName=FDSI
spring.data.mongodb.database=ecieserves_test

jwt.secret=62b9a6a5e7843c67c7e8ee2900a645059e59342c3a12d4debf9e173c732f2b87